 CREATE DATABASE VENDAS;
 USE VENDAS;
CREATE TABLE PRODUTOS(
    ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DECRICAO VARCHAR(30),
    ESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DOUBLE,
    PRECO_DESCONTO DOUBLE
    );
   
 CREATE TABLE VENDA(
 
    ID_VENDA INT NOT  NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VENDA INT NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT
   
 );
 
 SELECT *FROM PRODUTOS;
 SELECT *FROM VENDA;
 
 -- criando triger que calcula o preco_desconto de um produto todas as vezes que um novo produto é inserido
 CREATE TRIGGER TR_DESCONTO BEFORE INSERT 
 ON PRODUTOS
 FOR EACH ROW 
 SET NEW.PRECO_DESCONTO = (NEW.PRECO_PRODUTO * 0.90);
 


 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUES ("Muniotr", 8, 250.00); 
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUES ("gabinete", 10, 110.00); 
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUES ("mause", 6, 36.00); 
 INSERT INTO PRODUTOS (DECRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUES ("teclado", 5, 54.00); 
 
  SELECT *FROM PRODUTOS;

  -- criando  trigger na Tabela Venda que atualiza o estoque de produtos após o cliente realizar uma compra
 CREATE TRIGGER TR_ATTESTOQUE AFTER INSERT 
 ON VENDA
 FOR EACH ROW 
 UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE
    WHERE ID_PRODUTO = NEW.ID_PRODUTO;
 
 
 INSERT INTO VENDA (NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES (12321, 1, 3);
 INSERT INTO VENDA (NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES (45654, 2, 4);
 INSERT INTO VENDA (NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES (78987, 3, 2);
 INSERT INTO VENDA (NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES (25852, 4, 4);

 SELECT *FROM VENDA;
 
-- criando triger triggers na Tabela Venda que reestabeleçe o estoque quando o cliente desistir da compra
CREATE TRIGGER TR_RTESTOQUE AFTER DELETE 
ON VENDA
FOR EACH ROW
UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO + OLD.QUANTIDADE
    WHERE ID_PRODUTO = OLD.ID_PRODUTO;

DELETE FROM VENDA WHERE ID_VENDA = 1;
 
SELECT *FROM PRODUTOS;

SELECT *FROM VENDA;

 
 